languageCode = "en-us"
title = "A11y Ref"
baseURL = "https://kerseyi.github.io/a11y-ref/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "A11y code patterns and resources"
  codePenUser = "iank"
